include: package:lint/analysis_options_package.yaml

analyzer:
  strong-mode:
    implicit-dynamic: false

linter:
  rules:
    prefer_const_constructors: false
    close_sinks: true
    sort_constructors_first: true

